require 'rails_helper'
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WikisController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Wiki. As you add validations to Wiki, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      title: Faker::Hipster.sentence(3, true, 2),
      body: Faker::Lorem.paragraph(2, true, 4),
      private: false
    }
  end

  let(:invalid_attributes) do
    {
      title: '',
      body: ''
    }
  end

  let(:user) { create(:user) }
  let!(:wiki) { create(:wiki, user: user) }

  describe 'GET #index' do
    it 'assigns all wikis as @wikis' do
      get :index
      expect(assigns(:wikis)).to eq([wiki])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested wiki as @wiki' do
      get :show, id: wiki.to_param
      expect(assigns(:wiki)).to eq(wiki)
    end
  end

  describe 'GET #new' do
    login_user
    it 'assigns a new wiki as @wiki' do
      get :new, {}
      expect(assigns(:wiki)).to be_a_new(Wiki)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested wiki as @wiki' do
      get :edit, id: wiki.to_param
      expect(assigns(:wiki)).to eq(wiki)
    end
  end

  describe 'POST #create' do
    login_user
    context 'with valid params' do
      it 'creates a new Wiki' do
        expect do
          post :create, wiki: valid_attributes
        end.to change(Wiki, :count).by(1)
      end

      it 'assigns a newly created wiki as @wiki' do
        post :create, wiki: valid_attributes
        expect(assigns(:wiki)).to be_a(Wiki)
        expect(assigns(:wiki)).to be_persisted
      end

      it 'redirects to the created wiki' do
        wiki.reload
        post :create, id: wiki.to_param, wiki: valid_attributes
        wiki.reload
        # expect(response).to redirect_to(wiki)
        assert_redirected_to wiki_path(assigns(:wiki))
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved wiki as @wiki' do
        post :create, wiki: invalid_attributes
        expect(assigns(:wiki)).to be_a_new(Wiki)
      end

      it "re-renders the 'new' template" do
        post :create, wiki: invalid_attributes
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      login_user
      let(:new_attributes) do
        {
          title: Faker::Hipster.sentence(3, true, 2),
          body: Faker::Lorem.paragraph(2, true, 4),
          private: false
        }
      end

      it 'updates the requested wiki' do
        put :update, id: wiki.to_param, wiki: new_attributes
        wiki.reload
        expect(response).to have_http_status(:redirect)
        expect(wiki.title).to eq(new_attributes[:title])
        expect(wiki.body).to eq(new_attributes[:body])
        expect(wiki.private).to eq(new_attributes[:private])
      end

      it 'assigns the requested wiki as @wiki' do
        put :update, id: wiki.to_param, wiki: valid_attributes
        expect(assigns(:wiki)).to eq(wiki)
      end

      it 'redirects to the wiki' do
        put :update, id: wiki.to_param, wiki: valid_attributes
        wiki.reload
        expect(response).to redirect_to(wiki)
      end
    end

    context 'with invalid params' do
      login_user
      it 'assigns the wiki as @wiki' do
        put :update, id: wiki.to_param, wiki: invalid_attributes
        expect(assigns(:wiki)).to eq(wiki)
      end

      it "re-renders the 'edit' template" do
        put :update, id: wiki.to_param, wiki: invalid_attributes
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    login_admin
    it 'destroys the requested wiki' do
      expect do
        delete :destroy, id: wiki.to_param
      end.to change(Wiki, :count).by(-1)
    end

    it 'redirects to the wikis list' do
      delete :destroy, id: wiki.to_param
      expect(response).to redirect_to(wikis_url)
    end
  end
end
